# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{faces}
  s.version = "0.6.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Pellant"]
  s.date = %q{2010-04-14}
  s.description = %q{Avatars made super simple.}
  s.email = %q{nick@silentale.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "faces.gemspec",
     "init.rb",
     "lib/faces.rb",
     "lib/providers/facebook.rb",
     "lib/providers/flickr.rb",
     "lib/providers/gravatar.rb",
     "lib/providers/highrise.rb",
     "lib/providers/twitter.rb",
     "test/providers/test_facebook.rb",
     "test/providers/test_flickr.rb",
     "test/providers/test_gravatar.rb",
     "test/providers/test_highrise.rb",
     "test/providers/test_twitter.rb",
     "test/test_faces.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/nickpellant/faces}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Faces manages external and internal avatar sources in one unified format.}
  s.test_files = [
    "test/providers/test_facebook.rb",
     "test/providers/test_flickr.rb",
     "test/providers/test_gravatar.rb",
     "test/providers/test_highrise.rb",
     "test/providers/test_twitter.rb",
     "test/test_faces.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

